#!/bin/bash

echo "🔐 R2 Credentials Setup"
echo "======================"
echo ""
echo "To scan your R2 bucket, you need API credentials."
echo ""
echo "📋 Where to find them:"
echo "  1. Go to: https://dash.cloudflare.com"
echo "  2. Go to: R2 → Settings → API Tokens"
echo "  3. Click 'Create API Token'"
echo "  4. Set Permissions: 'Admin Read' (for listing objects)"
echo "  5. Copy the Access Key ID and Secret Access Key"
echo ""
echo "🔑 Then run:"
echo "  export CLOUDFLARE_R2_ACCESS_KEY='your_access_key_id'"
echo "  export CLOUDFLARE_R2_SECRET_KEY='your_secret_access_key'"
echo "  node ~/Documents/auto-generate-r2-mapping.js"
echo ""
echo "Or pass them directly:"
echo "  node ~/Documents/auto-generate-r2-mapping.js YOUR_KEY YOUR_SECRET"
echo ""
