"""reconcile schema drift: missing tables, assessment cols, enum/tz types

Revision ID: 3df0ff081f43
Revises: 84d7f25bb018
Create Date: 2026-06-13 03:43:08.981137
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.models._types  # EncryptedText/EncryptedJSON custom column types

# revision identifiers, used by Alembic.
revision: str = '3df0ff081f43'
down_revision: Union[str, None] = '84d7f25bb018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the PG enum types up front (checkfirst so this is safe on DBs where
    # an earlier path already created them); the column ops below reference them.
    bind = op.get_bind()
    sa.Enum('approval', 'advisory', 'escalate', name='decision_type').create(bind, checkfirst=True)
    sa.Enum('received', 'processing', 'ready_for_download', 'completed', name='dsar_status').create(bind, checkfirst=True)
    sa.Enum('coherence', 'consistency', 'fidelity', 'bias_check', name='gate_name').create(bind, checkfirst=True)

    op.create_table('email_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_email', sa.String(length=254), nullable=False),
    sa.Column('template_name', sa.String(length=50), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_logs_assessment_id', 'email_logs', ['assessment_id'], unique=False)
    op.create_index('ix_email_logs_recipient', 'email_logs', ['recipient_email'], unique=False)
    op.create_index('ix_email_logs_sent_at', 'email_logs', ['sent_at'], unique=False)
    op.create_index('ix_email_logs_status', 'email_logs', ['status'], unique=False)
    op.create_index('ix_email_logs_template', 'email_logs', ['template_name'], unique=False)
    op.create_table('disparate_impact_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('analysis_period', sa.String(length=255), nullable=False),
    sa.Column('demographic_group', sa.String(length=128), nullable=False),
    sa.Column('population_size', sa.Integer(), nullable=False),
    sa.Column('selection_rate', sa.Float(), nullable=False),
    sa.Column('reference_group', sa.String(length=128), nullable=False),
    sa.Column('reference_selection_rate', sa.Float(), nullable=False),
    sa.Column('four_fifths_ratio', sa.Float(), nullable=False),
    sa.Column('is_disparate_impact', sa.Boolean(), nullable=False),
    sa.Column('analysis_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_disparate_impact_analyses_created_at', 'disparate_impact_analyses', ['created_at'], unique=False)
    op.create_index('ix_disparate_impact_analyses_position_id', 'disparate_impact_analyses', ['position_id'], unique=False)
    op.create_table('disparate_impact_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('flag_triggered', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('affected_group', sa.String(length=128), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_disparate_impact_flags_assessment_id', 'disparate_impact_flags', ['assessment_id'], unique=False)
    op.create_index('ix_disparate_impact_flags_created_at', 'disparate_impact_flags', ['created_at'], unique=False)
    op.alter_column('applications', 'stage',
               existing_type=postgresql.ENUM('applied', 'phone_screen', 'technical', 'onsite', 'offer', 'hired', 'rejected', name='pipeline_stage'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'applied'::pipeline_stage"))
    op.drop_index(op.f('ix_applications_resume_id'), table_name='applications')
    op.add_column('assessments', sa.Column('dlq_error', app.models._types.EncryptedText(), nullable=True))
    op.add_column('assessments', sa.Column('dlq_context', app.models._types.EncryptedJSON(), nullable=True))
    op.add_column('assessments', sa.Column('decision_type', postgresql.ENUM('approval', 'advisory', 'escalate', name='decision_type', create_type=False), nullable=True))
    # server_default so adding these NOT NULL columns is safe on a DB that
    # already has assessment rows.
    op.add_column('assessments', sa.Column('human_review_required', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('assessments', sa.Column('article_14_compliant', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('assessments', sa.Column('review_reason', sa.Text(), nullable=True))
    op.create_index('ix_assessments_decision_type', 'assessments', ['decision_type'], unique=False)
    op.drop_column('assessments', 'gates_passed_at')
    op.drop_column('assessments', 'governance_status')
    op.drop_index(op.f('ix_capability_mapping_confidence'), table_name='capability_mapping')
    op.drop_index(op.f('ix_capability_mapping_keyword'), table_name='capability_mapping')
    op.create_index(op.f('ix_capability_mapping_confidence_score'), 'capability_mapping', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_capability_mapping_cv_keyword'), 'capability_mapping', ['cv_keyword'], unique=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('chat_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_chat_session_memories_session_id'), table_name='chat_session_memories')
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_credential_mapping_score'), table_name='credential_mapping')
    op.create_index(op.f('ix_credential_mapping_match_score'), 'credential_mapping', ['match_score'], unique=False)
    op.alter_column('dsar_requests', 'status',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('received', 'processing', 'ready_for_download', 'completed', name='dsar_status', create_type=False),
               existing_nullable=False,
               postgresql_using='status::dsar_status')
    op.alter_column('governance_logs', 'gate_name',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('coherence', 'consistency', 'fidelity', 'bias_check', name='gate_name', create_type=False),
               existing_nullable=False,
               postgresql_using='gate_name::gate_name')
    op.drop_index(op.f('ix_governance_logs_gate_name'), table_name='governance_logs')
    op.alter_column('governance_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('governance_reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # Drop the jsonb default before the type change, cast via an empty array
    # (the column starts empty on a fresh DB), then restore an array default.
    op.alter_column('interviews', 'interviewer_ids', server_default=None,
               existing_type=postgresql.JSONB(astext_type=sa.Text()))
    op.alter_column('interviews', 'interviewer_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.ARRAY(sa.UUID()),
               nullable=False,
               postgresql_using="'{}'::uuid[]",
               server_default=sa.text("'{}'::uuid[]"))
    op.drop_index(op.f('ix_job_deduplication_ingest_queue_item_id'), table_name='job_deduplication')
    op.drop_constraint(op.f('job_deduplication_fingerprint_key'), 'job_deduplication', type_='unique')
    op.drop_index(op.f('ix_job_deduplication_fingerprint'), table_name='job_deduplication')
    op.create_index(op.f('ix_job_deduplication_fingerprint'), 'job_deduplication', ['fingerprint'], unique=True)
    op.drop_index(op.f('ix_job_scraping_config_enabled'), table_name='job_scraping_config')
    op.drop_index(op.f('ix_job_scraping_config_source_type'), table_name='job_scraping_config')
    op.drop_index(op.f('ix_mass_upload_batch_status'), table_name='mass_upload_batch')
    op.drop_index(op.f('ix_mass_upload_batch_user_id'), table_name='mass_upload_batch')
    op.drop_constraint(op.f('mass_upload_batch_user_id_fkey'), 'mass_upload_batch', type_='foreignkey')
    op.alter_column('notification_preferences', 'notification_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("jsonb_build_object('interview_scheduled', true, 'scorecard_request', true, 'candidate_advanced', true, 'pipeline_update', true, 'system_alerts', true)"))
    op.create_index('ix_notifications_delivered', 'notifications', ['delivered'], unique=False)
    op.drop_index(op.f('ix_scraping_run_config_id'), table_name='scraping_run')
    op.drop_index(op.f('ix_scraping_run_status'), table_name='scraping_run')
    op.drop_constraint(op.f('scraping_run_config_id_fkey'), 'scraping_run', type_='foreignkey')
    op.drop_index(op.f('ix_training_chat_messages_created_at'), table_name='training_chat_messages')
    op.drop_index(op.f('ix_training_chat_messages_session_id'), table_name='training_chat_messages')
    op.drop_index(op.f('ix_training_chat_messages_user_id'), table_name='training_chat_messages')
    op.drop_constraint(op.f('training_chat_messages_user_id_fkey'), 'training_chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'training_chat_messages', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_training_data_items_applied'), table_name='training_data_items')
    op.drop_index(op.f('ix_training_data_items_decision'), table_name='training_data_items')
    op.drop_index(op.f('ix_training_data_items_upload_id'), table_name='training_data_items')
    op.drop_constraint(op.f('training_data_items_upload_id_fkey'), 'training_data_items', type_='foreignkey')
    op.create_foreign_key(None, 'training_data_items', 'training_data_uploads', ['upload_id'], ['id'])
    op.drop_index(op.f('ix_training_data_uploads_created_at'), table_name='training_data_uploads')
    op.drop_index(op.f('ix_training_data_uploads_status'), table_name='training_data_uploads')
    op.drop_index(op.f('ix_training_data_uploads_user_id'), table_name='training_data_uploads')
    op.drop_constraint(op.f('training_data_uploads_user_id_fkey'), 'training_data_uploads', type_='foreignkey')
    op.create_foreign_key(None, 'training_data_uploads', 'users', ['user_id'], ['id'])
    op.alter_column('training_feedback', 'feedback_type',
               existing_type=postgresql.ENUM('hire', 'reject', 'maybe', 'interested', 'not_interested', 'applied', name='feedback_type'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('training_feedback', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'web'::character varying"))
    op.alter_column('training_feedback', 'is_training',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_training_insight_batches_created_at'), table_name='training_insight_batches')
    op.drop_index(op.f('ix_training_insight_batches_source'), table_name='training_insight_batches')
    op.drop_index(op.f('ix_training_learning_sessions_created_at'), table_name='training_learning_sessions')
    op.drop_index(op.f('ix_training_learning_sessions_status'), table_name='training_learning_sessions')
    op.drop_index(op.f('ix_training_learning_sessions_user_id'), table_name='training_learning_sessions')
    op.drop_constraint(op.f('training_learning_sessions_user_id_fkey'), 'training_learning_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'training_learning_sessions', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_training_progress_metric_name'), 'training_progress', ['metric_name'], unique=False)
    op.drop_index(op.f('ix_upload_field_mapping_is_system'), table_name='upload_field_mapping')
    op.drop_index(op.f('ix_upload_field_mapping_name'), table_name='upload_field_mapping')
    op.drop_constraint(op.f('upload_field_mapping_created_by_fkey'), 'upload_field_mapping', type_='foreignkey')
    op.drop_index(op.f('ix_virtual_brain_state_active'), table_name='virtual_brain_state')
    op.create_index(op.f('ix_virtual_brain_state_is_active'), 'virtual_brain_state', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtual_brain_state_is_active'), table_name='virtual_brain_state')
    op.create_index(op.f('ix_virtual_brain_state_active'), 'virtual_brain_state', ['is_active'], unique=False)
    op.create_foreign_key(op.f('upload_field_mapping_created_by_fkey'), 'upload_field_mapping', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_upload_field_mapping_name'), 'upload_field_mapping', ['name'], unique=False)
    op.create_index(op.f('ix_upload_field_mapping_is_system'), 'upload_field_mapping', ['is_system'], unique=False)
    op.drop_index(op.f('ix_training_progress_metric_name'), table_name='training_progress')
    op.drop_constraint(None, 'training_learning_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('training_learning_sessions_user_id_fkey'), 'training_learning_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_training_learning_sessions_user_id'), 'training_learning_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_training_learning_sessions_status'), 'training_learning_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_training_learning_sessions_created_at'), 'training_learning_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_training_insight_batches_source'), 'training_insight_batches', ['source'], unique=False)
    op.create_index(op.f('ix_training_insight_batches_created_at'), 'training_insight_batches', ['created_at'], unique=False)
    op.alter_column('training_feedback', 'is_training',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('training_feedback', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'web'::character varying"))
    op.alter_column('training_feedback', 'feedback_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('hire', 'reject', 'maybe', 'interested', 'not_interested', 'applied', name='feedback_type'),
               existing_nullable=False)
    op.drop_constraint(None, 'training_data_uploads', type_='foreignkey')
    op.create_foreign_key(op.f('training_data_uploads_user_id_fkey'), 'training_data_uploads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_training_data_uploads_user_id'), 'training_data_uploads', ['user_id'], unique=False)
    op.create_index(op.f('ix_training_data_uploads_status'), 'training_data_uploads', ['status'], unique=False)
    op.create_index(op.f('ix_training_data_uploads_created_at'), 'training_data_uploads', ['created_at'], unique=False)
    op.drop_constraint(None, 'training_data_items', type_='foreignkey')
    op.create_foreign_key(op.f('training_data_items_upload_id_fkey'), 'training_data_items', 'training_data_uploads', ['upload_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_training_data_items_upload_id'), 'training_data_items', ['upload_id'], unique=False)
    op.create_index(op.f('ix_training_data_items_decision'), 'training_data_items', ['decision'], unique=False)
    op.create_index(op.f('ix_training_data_items_applied'), 'training_data_items', ['applied_to_training'], unique=False)
    op.drop_constraint(None, 'training_chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('training_chat_messages_user_id_fkey'), 'training_chat_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_training_chat_messages_user_id'), 'training_chat_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_training_chat_messages_session_id'), 'training_chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_training_chat_messages_created_at'), 'training_chat_messages', ['created_at'], unique=False)
    op.create_foreign_key(op.f('scraping_run_config_id_fkey'), 'scraping_run', 'job_scraping_config', ['config_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_scraping_run_status'), 'scraping_run', ['status'], unique=False)
    op.create_index(op.f('ix_scraping_run_config_id'), 'scraping_run', ['config_id'], unique=False)
    op.drop_index('ix_notifications_delivered', table_name='notifications')
    op.alter_column('notification_preferences', 'notification_types',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("jsonb_build_object('interview_scheduled', true, 'scorecard_request', true, 'candidate_advanced', true, 'pipeline_update', true, 'system_alerts', true)"))
    op.create_foreign_key(op.f('mass_upload_batch_user_id_fkey'), 'mass_upload_batch', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_mass_upload_batch_user_id'), 'mass_upload_batch', ['user_id'], unique=False)
    op.create_index(op.f('ix_mass_upload_batch_status'), 'mass_upload_batch', ['status'], unique=False)
    op.create_index(op.f('ix_job_scraping_config_source_type'), 'job_scraping_config', ['source_type'], unique=False)
    op.create_index(op.f('ix_job_scraping_config_enabled'), 'job_scraping_config', ['enabled'], unique=False)
    op.drop_index(op.f('ix_job_deduplication_fingerprint'), table_name='job_deduplication')
    op.create_index(op.f('ix_job_deduplication_fingerprint'), 'job_deduplication', ['fingerprint'], unique=False)
    op.create_unique_constraint(op.f('job_deduplication_fingerprint_key'), 'job_deduplication', ['fingerprint'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_job_deduplication_ingest_queue_item_id'), 'job_deduplication', ['ingest_queue_item_id'], unique=False)
    op.alter_column('interviews', 'interviewer_ids',
               existing_type=sa.ARRAY(sa.UUID()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('governance_reviews', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('governance_reviews', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_index(op.f('ix_governance_logs_gate_name'), 'governance_logs', ['gate_name'], unique=False)
    op.alter_column('governance_logs', 'gate_name',
               existing_type=sa.Enum('coherence', 'consistency', 'fidelity', 'bias_check', name='gate_name'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('dsar_requests', 'status',
               existing_type=sa.Enum('received', 'processing', 'ready_for_download', 'completed', name='dsar_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_credential_mapping_match_score'), table_name='credential_mapping')
    op.create_index(op.f('ix_credential_mapping_score'), 'credential_mapping', ['match_score'], unique=False)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_index(op.f('ix_chat_session_memories_session_id'), 'chat_session_memories', ['session_id'], unique=False)
    op.alter_column('chat_messages', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_capability_mapping_cv_keyword'), table_name='capability_mapping')
    op.drop_index(op.f('ix_capability_mapping_confidence_score'), table_name='capability_mapping')
    op.create_index(op.f('ix_capability_mapping_keyword'), 'capability_mapping', ['cv_keyword'], unique=False)
    op.create_index(op.f('ix_capability_mapping_confidence'), 'capability_mapping', ['confidence_score'], unique=False)
    op.add_column('assessments', sa.Column('governance_status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('gates_passed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index('ix_assessments_decision_type', table_name='assessments')
    op.drop_column('assessments', 'review_reason')
    op.drop_column('assessments', 'article_14_compliant')
    op.drop_column('assessments', 'human_review_required')
    op.drop_column('assessments', 'decision_type')
    op.drop_column('assessments', 'dlq_context')
    op.drop_column('assessments', 'dlq_error')
    op.create_index(op.f('ix_applications_resume_id'), 'applications', ['resume_id'], unique=False)
    op.alter_column('applications', 'stage',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('applied', 'phone_screen', 'technical', 'onsite', 'offer', 'hired', 'rejected', name='pipeline_stage'),
               existing_nullable=False,
               existing_server_default=sa.text("'applied'::pipeline_stage"))
    op.drop_index('ix_disparate_impact_flags_created_at', table_name='disparate_impact_flags')
    op.drop_index('ix_disparate_impact_flags_assessment_id', table_name='disparate_impact_flags')
    op.drop_table('disparate_impact_flags')
    op.drop_index('ix_disparate_impact_analyses_position_id', table_name='disparate_impact_analyses')
    op.drop_index('ix_disparate_impact_analyses_created_at', table_name='disparate_impact_analyses')
    op.drop_table('disparate_impact_analyses')
    op.drop_index('ix_email_logs_template', table_name='email_logs')
    op.drop_index('ix_email_logs_status', table_name='email_logs')
    op.drop_index('ix_email_logs_sent_at', table_name='email_logs')
    op.drop_index('ix_email_logs_recipient', table_name='email_logs')
    op.drop_index('ix_email_logs_assessment_id', table_name='email_logs')
    op.drop_table('email_logs')
    # ### end Alembic commands ###
