"""Execute agent actions against the system."""
import logging

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.user import User
from app.services.action_handlers import get_handler_for_action

logger = logging.getLogger(__name__)


# Informational, side-effect-free actions that should run immediately even in
# manual mode — they only surface information (e.g. a clarifying question) and
# never need user confirmation.
_ALWAYS_EXECUTE = {"clarify"}


class ActionExecutor:
    """Executes actions generated by agents using real handlers."""

    @staticmethod
    async def execute_actions(
        actions: list[dict],
        user: User,
        db: AsyncSession,
        autonomous: bool = False,
    ) -> list[dict]:
        """Execute a list of actions and return results.

        Args:
            actions: List of action dicts from agent response
            user: User performing the action
            db: Database session
            autonomous: If True, execute actions autonomously. If False, mark as pending.

        Returns:
            Updated actions with execution results
        """
        results = []

        for action in actions:
            try:
                if autonomous or action.get("type", "").lower() in _ALWAYS_EXECUTE:
                    # Autonomous mode, or a side-effect-free informational action
                    # (e.g. clarify): execute immediately using real handlers.
                    result = await ActionExecutor._execute_single(action, user, db)
                    results.append(result)
                else:
                    # In manual mode, mark as pending for user confirmation
                    action["status"] = "pending"
                    action["autonomous_mode"] = False
                    logger.info(
                        "Action marked pending for user confirmation",
                        extra={"action_id": action.get("id"), "type": action.get("type")},
                    )
                    results.append(action)
            except Exception as e:
                logger.error(f"Action execution failed: {e}", extra={"action_id": action.get("id")})
                action["status"] = "failed"
                action["result"] = str(e)
                results.append(action)

        return results

    @staticmethod
    async def _execute_single(action: dict, user: User, db: AsyncSession) -> dict:
        """Execute a single action using the appropriate handler.

        Args:
            action: Action dict with id, description, type, parameters
            user: User performing action
            db: Database session

        Returns:
            Action with updated status and result
        """
        action_type = action.get("type", "").lower()

        # Get handler for this action type
        handler = await get_handler_for_action(action_type)

        if handler:
            # Use real handler
            logger.info(
                f"Executing {action_type} action",
                extra={"action_id": action.get("id"), "type": action_type},
            )
            action = await handler.handle(action, user, db)
        else:
            # Unknown action type - log and mark as pending for review
            logger.warning(
                f"Unknown action type: {action_type}",
                extra={"action_id": action.get("id")},
            )
            action["status"] = "pending"
            action["result"] = f"Unknown action type '{action_type}' - manual review required"

        return action
